
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkyngrrirhfurmdcejzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreW5ncnJpcmhmdXJtZGNlanprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTI2MDcsImV4cCI6MjA1OTc2ODYwN30.BYAekbDdO6AXRX_4f5VtMDOWGoKYkQz7qh9hqG7aIRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Get current site origin for redirects
const siteUrl = window.location.origin;

// Create Supabase client with properly configured auth options
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'gradenexus-auth-token',
    flowType: 'pkce',
  }
});
